import json

path = 'backend/config/domain-priors/exact.json'
with open(path, encoding='utf-8') as f:
    data = json.load(f)

additions = {
  # ── Newspaper: Major US news ──────────────────────────────────────────────
  "theguardian.com": "Newspaper",
  "washingtonpost.com": "Newspaper",
  "usatoday.com": "Newspaper",
  "reuters.com": "Newspaper",
  "apnews.com": "Newspaper",
  "latimes.com": "Newspaper",
  "nypost.com": "Newspaper",
  "chicagotribune.com": "Newspaper",
  "bostonglobe.com": "Newspaper",
  "sfchronicle.com": "Newspaper",
  "seattletimes.com": "Newspaper",
  "denverpost.com": "Newspaper",
  "dallasnews.com": "Newspaper",
  "ajc.com": "Newspaper",
  "startribune.com": "Newspaper",
  "azcentral.com": "Newspaper",
  "oregonlive.com": "Newspaper",
  "nj.com": "Newspaper",
  "cleveland.com": "Newspaper",
  "al.com": "Newspaper",
  "mlive.com": "Newspaper",
  "pennlive.com": "Newspaper",
  "mcall.com": "Newspaper",
  "miamiherald.com": "Newspaper",
  "tampabay.com": "Newspaper",
  "sun-sentinel.com": "Newspaper",
  "orlandosentinel.com": "Newspaper",

  # ── Newspaper: UK/International ───────────────────────────────────────────
  "dailymail.co.uk": "Newspaper",
  "independent.co.uk": "Newspaper",
  "thesun.co.uk": "Newspaper",
  "mirror.co.uk": "Newspaper",
  "express.co.uk": "Newspaper",
  "metro.co.uk": "Newspaper",
  "standard.co.uk": "Newspaper",
  "ft.com": "Newspaper",
  "newstatesman.com": "Newspaper",
  "spectator.co.uk": "Newspaper",
  "abc.net.au": "Newspaper",
  "smh.com.au": "Newspaper",
  "theage.com.au": "Newspaper",
  "news.com.au": "Newspaper",
  "theaustralian.com.au": "Newspaper",
  "irishtimes.com": "Newspaper",
  "irishexaminer.com": "Newspaper",
  "rte.ie": "Newspaper",
  "globeandmail.com": "Newspaper",
  "nationalpost.com": "Newspaper",
  "cbc.ca": "Newspaper",
  "thestar.com": "Newspaper",
  "hindustantimes.com": "Newspaper",
  "thehindu.com": "Newspaper",
  "ndtv.com": "Newspaper",
  "timesofindia.indiatimes.com": "Newspaper",
  "livemint.com": "Newspaper",
  "economictimes.indiatimes.com": "Newspaper",
  "scmp.com": "Newspaper",
  "japantimes.co.jp": "Newspaper",

  # ── Newspaper: Business / Finance media ───────────────────────────────────
  "businessinsider.com": "Newspaper",
  "fortune.com": "Newspaper",
  "inc.com": "Newspaper",
  "entrepreneur.com": "Newspaper",
  "fastcompany.com": "Newspaper",
  "qz.com": "Newspaper",
  "hbr.org": "Newspaper",
  "marketwatch.com": "Newspaper",
  "barrons.com": "Newspaper",
  "cnbc.com": "Newspaper",
  "moneymorning.com": "Newspaper",

  # ── Newspaper: Politics / General interest ────────────────────────────────
  "politico.com": "Newspaper",
  "axios.com": "Newspaper",
  "thehill.com": "Newspaper",
  "huffpost.com": "Newspaper",
  "vox.com": "Newspaper",
  "theatlantic.com": "Newspaper",
  "newyorker.com": "Newspaper",
  "time.com": "Newspaper",
  "slate.com": "Newspaper",
  "salon.com": "Newspaper",
  "buzzfeed.com": "Newspaper",
  "buzzfeednews.com": "Newspaper",
  "vice.com": "Newspaper",
  "motherjones.com": "Newspaper",
  "thenation.com": "Newspaper",
  "reason.com": "Newspaper",
  "nationalreview.com": "Newspaper",

  # ── Newspaper: Tech media ─────────────────────────────────────────────────
  "techcrunch.com": "Newspaper",
  "theverge.com": "Newspaper",
  "wired.com": "Newspaper",
  "arstechnica.com": "Newspaper",
  "cnet.com": "Newspaper",
  "zdnet.com": "Newspaper",
  "engadget.com": "Newspaper",
  "gizmodo.com": "Newspaper",
  "venturebeat.com": "Newspaper",
  "mashable.com": "Newspaper",
  "thenextweb.com": "Newspaper",
  "appleinsider.com": "Newspaper",
  "slashdot.org": "Newspaper",
  "theregister.com": "Newspaper",
  "computerworld.com": "Newspaper",
  "infoworld.com": "Newspaper",

  # ── Newspaper: Entertainment / Culture ────────────────────────────────────
  "variety.com": "Newspaper",
  "hollywoodreporter.com": "Newspaper",
  "deadline.com": "Newspaper",
  "ew.com": "Newspaper",
  "people.com": "Newspaper",
  "tmz.com": "Newspaper",
  "usmagazine.com": "Newspaper",
  "rollingstone.com": "Newspaper",
  "pitchfork.com": "Newspaper",
  "vulture.com": "Newspaper",
  "indiewire.com": "Newspaper",
  "empireonline.com": "Newspaper",
  "screendaily.com": "Newspaper",

  # ── Newspaper: Fashion / Lifestyle ────────────────────────────────────────
  "elle.com": "Newspaper",
  "vogue.com": "Newspaper",
  "harpersbazaar.com": "Newspaper",
  "cosmopolitan.com": "Newspaper",
  "allure.com": "Newspaper",
  "glamour.com": "Newspaper",
  "instyle.com": "Newspaper",
  "refinery29.com": "Newspaper",
  "popsugar.com": "Newspaper",
  "thecut.com": "Newspaper",
  "whowhatwear.com": "Newspaper",
  "byrdie.com": "Newspaper",
  "marieclaire.com": "Newspaper",
  "wmagazine.com": "Newspaper",
  "townandcountrymag.com": "Newspaper",
  "harpersbazaar.co.uk": "Newspaper",
  "stylist.co.uk": "Newspaper",

  # ── Newspaper: Sports ─────────────────────────────────────────────────────
  "espn.com": "Newspaper",
  "cbssports.com": "Newspaper",
  "nbcsports.com": "Newspaper",
  "bleacherreport.com": "Newspaper",
  "si.com": "Newspaper",
  "sportingnews.com": "Newspaper",
  "theathletic.com": "Newspaper",
  "deadspin.com": "Newspaper",
  "sbnation.com": "Newspaper",
  "skysports.com": "Newspaper",
  "goal.com": "Newspaper",
  "90min.com": "Newspaper",
  "givemesport.com": "Newspaper",
  "fourfourtwo.com": "Newspaper",
  "talksport.com": "Newspaper",
  "cbssports.com": "Newspaper",
  "nfl.com": "Newspaper",
  "mlb.com": "Newspaper",
  "nba.com": "Newspaper",
  "nhl.com": "Newspaper",

  # ── Newspaper: Health / Wellness ──────────────────────────────────────────
  "medicalnewstoday.com": "Newspaper",
  "prevention.com": "Newspaper",
  "health.com": "Newspaper",
  "runnersworld.com": "Newspaper",
  "bicycling.com": "Newspaper",
  "triathlete.com": "Newspaper",

  # ── Newspaper: Science ────────────────────────────────────────────────────
  "scientificamerican.com": "Newspaper",
  "livescience.com": "Newspaper",
  "space.com": "Newspaper",
  "phys.org": "Newspaper",
  "popularmechanics.com": "Newspaper",
  "popsci.com": "Newspaper",
  "newscientist.com": "Newspaper",
  "discovermagazine.com": "Newspaper",
  "smithsonianmag.com": "Newspaper",
  "nationalgeographic.com": "Newspaper",
  "nature.com": "Newspaper",
  "sciencedaily.com": "Newspaper",
  "iflscience.com": "Newspaper",

  # ── Newspaper: Food ───────────────────────────────────────────────────────
  "bonappetit.com": "Newspaper",
  "tastingtable.com": "Newspaper",
  "eatingwell.com": "Newspaper",
  "foodandwine.com": "Newspaper",
  "seriouseats.com": "Newspaper",
  "delish.com": "Newspaper",
  "saveur.com": "Newspaper",

  # ── Newspaper: Travel ─────────────────────────────────────────────────────
  "cntraveler.com": "Newspaper",
  "afar.com": "Newspaper",
  "nationalgeographic.com/travel": "Newspaper",
  "travelchannel.com": "Newspaper",

  # ── Newspaper: Home / Design ──────────────────────────────────────────────
  "dwell.com": "Newspaper",
  "thisoldhouse.com": "Newspaper",
  "familyhandyman.com": "Newspaper",
  "countryliving.com": "Newspaper",
  "goodhousekeeping.com": "Newspaper",
  "womansday.com": "Newspaper",
  "realsimple.com": "Newspaper",
  "bhg.com": "Newspaper",
  "elledecor.com": "Newspaper",

  # ── Blog / Review sites ───────────────────────────────────────────────────
  "wirecutter.com": "Blog",
  "consumerreports.org": "Blog",
  "pcmag.com": "Blog",
  "tomshardware.com": "Blog",
  "tomsguide.com": "Blog",
  "techradar.com": "Blog",
  "makeuseof.com": "Blog",
  "howtogeek.com": "Blog",
  "lifehacker.com": "Blog",
  "notebookcheck.net": "Blog",
  "gsmarena.com": "Blog",
  "phonearena.com": "Blog",
  "9to5mac.com": "Blog",
  "9to5google.com": "Blog",
  "macrumors.com": "Blog",
  "androidauthority.com": "Blog",
  "xda-developers.com": "Blog",
  "dpreview.com": "Blog",
  "photographylife.com": "Blog",
  "thephoblographer.com": "Blog",
  "neilpatel.com": "Blog",
  "backlinko.com": "Blog",
  "searchengineland.com": "Blog",
  "searchenginejournal.com": "Blog",
  "seroundtable.com": "Blog",
  "socialmediaexaminer.com": "Blog",
  "sproutsocial.com": "Blog",
  "copyblogger.com": "Blog",
  "smartpassiveincome.com": "Blog",
  "authorityhacker.com": "Blog",
  "incomeschool.com": "Blog",
  "switchbacktravel.com": "Blog",
  "cleverhiker.com": "Blog",
  "gearpatrol.com": "Blog",
  "bikeradar.com": "Blog",
  "cyclingnews.com": "Blog",
  "pinkbike.com": "Blog",
  "singletracks.com": "Blog",
  "trailforks.com": "Blog",
  "irunfar.com": "Blog",
  "runnerclick.com": "Blog",
  "blistergearreview.com": "Blog",
  "nerdwallet.com": "Blog",
  "bankrate.com": "Blog",
  "thepointsguy.com": "Blog",
  "moneyunder30.com": "Blog",
  "doughroller.net": "Blog",
  "thesimpledollar.com": "Blog",
  "epicurious.com": "Blog",
  "thekitchn.com": "Blog",
  "simplyrecipes.com": "Blog",
  "food52.com": "Blog",
  "allrecipes.com": "Blog",
  "tasteofhome.com": "Blog",
  "cookingclassy.com": "Blog",
  "sallysbakingaddiction.com": "Blog",
  "minimalistbaker.com": "Blog",
  "halfbakedharvest.com": "Blog",
  "apartmenttherapy.com": "Blog",
  "bobvila.com": "Blog",
  "gardeningknowhow.com": "Blog",
  "reddit.com": "Blog",
  "quora.com": "Blog",
  "medium.com": "Blog",
  "livestrong.com": "Blog",
  "mindbodygreen.com": "Blog",
  "verywellhealth.com": "Blog",
  "verywellmind.com": "Blog",
  "verywellfamily.com": "Blog",
  "everydayhealth.com": "Blog",

  # ── E-commerce: Fashion / Apparel ─────────────────────────────────────────
  "asos.com": "E-commerce",
  "hm.com": "E-commerce",
  "zara.com": "E-commerce",
  "uniqlo.com": "E-commerce",
  "gap.com": "E-commerce",
  "oldnavy.com": "E-commerce",
  "bananarepublic.com": "E-commerce",
  "jcrew.com": "E-commerce",
  "anthropologie.com": "E-commerce",
  "freepeople.com": "E-commerce",
  "urbanoutfitters.com": "E-commerce",
  "revolve.com": "E-commerce",
  "shein.com": "E-commerce",
  "temu.com": "E-commerce",
  "forever21.com": "E-commerce",
  "express.com": "E-commerce",
  "guess.com": "E-commerce",
  "ralphlauren.com": "E-commerce",
  "tommyhilfiger.com": "E-commerce",
  "calvinklein.com": "E-commerce",
  "lacoste.com": "E-commerce",
  "levi.com": "E-commerce",
  "carhartt.com": "E-commerce",
  "shopbop.com": "E-commerce",
  "farfetch.com": "E-commerce",
  "net-a-porter.com": "E-commerce",
  "ssense.com": "E-commerce",
  "mytheresa.com": "E-commerce",
  "mango.com": "E-commerce",
  "aritzia.com": "E-commerce",
  "lululemon.com": "E-commerce",
  "gymshark.com": "E-commerce",
  "vuori.com": "E-commerce",
  "fabletics.com": "E-commerce",
  "allbirds.com": "E-commerce",
  "on-running.com": "E-commerce",
  "on.com": "E-commerce",
  "salomon.com": "E-commerce",
  "merrell.com": "E-commerce",
  "mizuno.com": "E-commerce",
  "altralrunning.com": "E-commerce",
  "puma.com": "E-commerce",
  "reebok.com": "E-commerce",
  "converse.com": "E-commerce",
  "vans.com": "E-commerce",
  "skechers.com": "E-commerce",
  "crocs.com": "E-commerce",
  "ugg.com": "E-commerce",
  "timberland.com": "E-commerce",
  "stevemadden.com": "E-commerce",
  "clarks.com": "E-commerce",
  "dsw.com": "E-commerce",
  "footlocker.com": "E-commerce",
  "finishline.com": "E-commerce",
  "champssports.com": "E-commerce",
  "academy.com": "E-commerce",
  "rei.com": "E-commerce",
  "backcountry.com": "E-commerce",
  "evo.com": "E-commerce",
  "moosejaw.com": "E-commerce",
  "patagonia.com": "E-commerce",
  "thenorthface.com": "E-commerce",
  "columbia.com": "E-commerce",
  "underarmour.com": "E-commerce",
  "arcteryx.com": "E-commerce",
  "mammut.com": "E-commerce",

  # ── E-commerce: Department stores ─────────────────────────────────────────
  "bloomingdales.com": "E-commerce",
  "saksfifthavenue.com": "E-commerce",
  "neimanmarcus.com": "E-commerce",
  "belk.com": "E-commerce",
  "kohls.com": "E-commerce",
  "jcpenney.com": "E-commerce",
  "samsclub.com": "E-commerce",
  "bjs.com": "E-commerce",
  "tjmaxx.com": "E-commerce",
  "marshalls.com": "E-commerce",
  "burlington.com": "E-commerce",
  "ross.com": "E-commerce",

  # ── E-commerce: Electronics / Tech ────────────────────────────────────────
  "apple.com": "E-commerce",
  "samsung.com": "E-commerce",
  "dell.com": "E-commerce",
  "hp.com": "E-commerce",
  "lenovo.com": "E-commerce",
  "asus.com": "E-commerce",
  "acer.com": "E-commerce",
  "msi.com": "E-commerce",
  "razer.com": "E-commerce",
  "logitech.com": "E-commerce",
  "corsair.com": "E-commerce",
  "bhphotovideo.com": "E-commerce",
  "adorama.com": "E-commerce",
  "sweetwater.com": "E-commerce",
  "guitarcenter.com": "E-commerce",
  "musiciansfriend.com": "E-commerce",
  "reverb.com": "E-commerce",
  "gamestop.com": "E-commerce",
  "microsoft.com": "E-commerce",

  # ── E-commerce: Beauty ────────────────────────────────────────────────────
  "dermstore.com": "E-commerce",
  "glossier.com": "E-commerce",
  "charlottetilbury.com": "E-commerce",
  "maccosmetics.com": "E-commerce",
  "clinique.com": "E-commerce",
  "esteelauder.com": "E-commerce",
  "sk-ii.com": "E-commerce",
  "spacenk.com": "E-commerce",
  "fentybeauty.com": "E-commerce",
  "patrickta.com": "E-commerce",
  "beautylish.com": "E-commerce",

  # ── E-commerce: Home / Furniture ──────────────────────────────────────────
  "cb2.com": "E-commerce",
  "crateandbarrel.com": "E-commerce",
  "westelm.com": "E-commerce",
  "potterybarn.com": "E-commerce",
  "rh.com": "E-commerce",
  "williams-sonoma.com": "E-commerce",
  "zgallerie.com": "E-commerce",
  "article.com": "E-commerce",
  "allmodern.com": "E-commerce",
  "jossandmain.com": "E-commerce",
  "birchlanetm.com": "E-commerce",
  "worldmarket.com": "E-commerce",
  "pier1.com": "E-commerce",
  "bedbathandbeyond.com": "E-commerce",
  "containerstore.com": "E-commerce",

  # ── E-commerce: Pet / Specialty ───────────────────────────────────────────
  "petsmart.com": "E-commerce",
  "1800petmeds.com": "E-commerce",
  "staples.com": "E-commerce",
  "officedepot.com": "E-commerce",
  "michaels.com": "E-commerce",
  "joann.com": "E-commerce",
  "hobbylobby.com": "E-commerce",
  "walmart.com/pharmacy": "E-commerce",
  "kroger.com": "E-commerce",
  "walgreens.com": "E-commerce",
  "cvs.com": "E-commerce",
  "target.com": "E-commerce",
  "zulily.com": "E-commerce",
  "groupon.com": "E-commerce",

  # ── Directory ─────────────────────────────────────────────────────────────
  "g2.com": "Directory",
  "capterra.com": "Directory",
  "trustpilot.com": "Directory",
  "sitejabber.com": "Directory",
  "indeed.com": "Directory",
  "glassdoor.com": "Directory",
  "monster.com": "Directory",
  "ziprecruiter.com": "Directory",
  "linkedin.com/jobs": "Directory",
  "homeadvisor.com": "Directory",
  "angieslist.com": "Directory",
  "porch.com": "Directory",
  "expertise.com": "Directory",
  "bark.com": "Directory",
  "bbb.org": "Directory",
  "superpages.com": "Directory",
  "manta.com": "Directory",
  "mapquest.com": "Directory",
  "opentable.com": "Directory",
  "resy.com": "Directory",
  "grubhub.com": "Directory",
  "doordash.com": "Directory",
  "ubereats.com": "Directory",
  "yelp.com/biz": "Directory",
  "foursquare.com": "Directory",
  "apartments.com": "Directory",
  "trulia.com": "Directory",
  "redfin.com": "Directory",
  "homes.com": "Directory",
  "compass.com": "Directory",
  "cargurus.com": "Directory",
  "carmax.com": "Directory",
  "truecar.com": "Directory",
  "edmunds.com": "Directory",
  "iseecars.com": "Directory",
  "producthunt.com": "Directory",
  "alternativeto.net": "Directory",
  "softwareadvice.com": "Directory",
  "getapp.com": "Directory",
  "trustradius.com": "Directory",

  # ── SaaS ──────────────────────────────────────────────────────────────────
  "adobe.com": "Saas",
  "canva.com": "Saas",
  "shopify.com": "Saas",
  "wix.com": "Saas",
  "squarespace.com": "Saas",
  "wordpress.com": "Saas",
  "webflow.com": "Saas",
  "mailchimp.com": "Saas",
  "constantcontact.com": "Saas",
  "activecampaign.com": "Saas",
  "klaviyo.com": "Saas",
  "zendesk.com": "Saas",
  "freshdesk.com": "Saas",
  "intercom.com": "Saas",
  "drift.com": "Saas",
  "helpscout.com": "Saas",
  "asana.com": "Saas",
  "trello.com": "Saas",
  "monday.com": "Saas",
  "clickup.com": "Saas",
  "basecamp.com": "Saas",
  "airtable.com": "Saas",
  "smartsheet.com": "Saas",
  "atlassian.com": "Saas",
  "zoom.us": "Saas",
  "dropbox.com": "Saas",
  "quickbooks.com": "Saas",
  "freshbooks.com": "Saas",
  "xero.com": "Saas",
  "wave.com": "Saas",
  "stripe.com": "Saas",
  "twilio.com": "Saas",
  "sendgrid.com": "Saas",
  "mailgun.com": "Saas",
  "cloudflare.com": "Saas",
  "digitalocean.com": "Saas",
  "vultr.com": "Saas",
  "hetzner.com": "Saas",
  "render.com": "Saas",
  "railway.app": "Saas",
  "fly.io": "Saas",
  "datadog.com": "Saas",
  "pagerduty.com": "Saas",
  "sentry.io": "Saas",
  "bugsnag.com": "Saas",
  "logrocket.com": "Saas",
  "hotjar.com": "Saas",
  "mixpanel.com": "Saas",
  "amplitude.com": "Saas",
  "segment.com": "Saas",
  "elastic.co": "Saas",
  "mongodb.com": "Saas",
  "supabase.com": "Saas",
  "planetscale.com": "Saas",
  "prisma.io": "Saas",
  "docker.com": "Saas",
  "grafana.com": "Saas",
  "hashicorp.com": "Saas",
  "terraform.io": "Saas",
  "postman.com": "Saas",
  "jfrog.com": "Saas",
  "bitbucket.org": "Saas",
  "circleci.com": "Saas",
  "travisci.com": "Saas",
  "semaphoreci.com": "Saas",
  "contentful.com": "Saas",
  "sanity.io": "Saas",
  "strapi.io": "Saas",
  "ghost.org": "Saas",
  "convertkit.com": "Saas",
  "beehiiv.com": "Saas",
  "spotify.com": "Saas",
  "apple.com/apple-music": "Saas",
  "netflix.com": "Saas",
  "hulu.com": "Saas",
  "disneyplus.com": "Saas",
  "hbomax.com": "Saas",
  "max.com": "Saas",
  "peacocktv.com": "Saas",
  "paramountplus.com": "Saas",
  "youtube.com": "Saas",
  "vimeo.com": "Saas",
  "twitch.tv": "Saas",
  "discord.com": "Saas",
  "reddit.com/r": "Saas",
  "instagram.com": "Saas",
  "twitter.com": "Saas",
  "x.com": "Saas",
  "facebook.com": "Saas",
  "tiktok.com": "Saas",
  "pinterest.com": "Saas",

  # ── Service ───────────────────────────────────────────────────────────────
  "webmd.com": "Service",
  "mayoclinic.org": "Service",
  "everydayhealth.com": "Service",
  "drugs.com": "Service",
  "rxlist.com": "Service",
  "medicinenet.com": "Service",
  "medlineplus.gov": "Service",
  "cdc.gov": "Service",
  "fda.gov": "Service",
  "nih.gov": "Service",
  "who.int": "Service",
  "nhs.uk": "Service",
  "ftc.gov": "Service",
  "sec.gov": "Service",
  "irs.gov": "Service",
  "usa.gov": "Service",
  "congress.gov": "Service",
  "medicare.gov": "Service",
  "healthcare.gov": "Service",
  "stackoverflow.com": "Service",
  "stackexchange.com": "Service",
  "superuser.com": "Service",
  "serverfault.com": "Service",
  "mathoverflow.net": "Service",
  "wolframalpha.com": "Service",
  "translate.google.com": "Service",
  "maps.google.com": "Service",
  "foodnetwork.com": "Service",
  "lonelyplanet.com": "Service",
  "fodors.com": "Service",
  "frommers.com": "Service",
  "theknot.com": "Service",
  "weddingwire.com": "Service",
  "zola.com": "Service",
  "ancestry.com": "Service",
  "23andme.com": "Service",
  "duolingo.com": "Service",
  "babbel.com": "Service",
  "rosettastone.com": "Service",
}

changed = 0
skipped = 0
for domain, site_type in additions.items():
    if domain not in data:
        data[domain] = site_type
        changed += 1
    else:
        skipped += 1

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2)

print(f'exact.json: added {changed} new priors, skipped {skipped} already-existing.')
print('Done!')
